### ISSUE TITLE
Hephaestus init fails in Cygwin MinTTY

### ISSUE THREAD

**Issue by Kexanone** [ArmaAchilles/AddonBuilder#32]
Tried Hephaestus init in Cygwin MinTTY, but instead of being able to write an answer, you get an error message:
```
$ Hephaestus init
Use the command line? (Y/N)

Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.
   at System.Console.ReadKey(Boolean intercept)
   at Hephaestus.Utilities.ConsoleUtility.AskYesNoQuestion(String question) in C:\Users\Uldis\Source\Repos\Hephaestus\Hephaestus\Utilities\ConsoleUtility.cs:line 14
   at Hephaestus.Utilities.ArgumentUtility.InitCommand() in C:\Users\Uldis\Source\Repos\Hephaestus\Hephaestus\Utilities\ArgumentUtility.cs:line 72
   at Hephaestus.Utilities.ArgumentUtility.Handle(String[] arguments) in C:\Users\Uldis\Source\Repos\Hephaestus\Hephaestus\Utilities\ArgumentUtility.cs:line 27
   at Hephaestus.Program.Main(String[] arguments) in C:\Users\Uldis\Source\Repos\Hephaestus\Hephaestus\Program.cs:line 19

```

**Comment by CreepPork** [comment]
Forgot to close issue.
